=== nikitun13/epam-training/task08-xml/src/test/resources/data/gems.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://training.by/gems"
        xmlns:tns="http://training.by/gems"
        elementFormDefault="qualified">
    <element name="gems">
        <complexType>
            <sequence>
                <element ref="tns:gem" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="gem" type="tns:Gem"/>
    <element name="synthetic-gem" type="tns:SyntheticGem" substitutionGroup="tns:gem"/>

    <complexType name="Gem">
        <sequence>
            <element name="name">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[A-Z][a-z]{1,14}"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="preciousness">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="precious"/>
                        <enumeration value="semiprecious"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="origin" type="string"/>

            <element name="visual-parameters" type="tns:VisualParameters"/>

            <element name="value" type="double"/>

            <element name="date" type="date"/>
        </sequence>

        <attribute name="id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="(x)\d{1,19}"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="VisualParameters">
        <sequence>
            <element name="color">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="red"/>
                        <enumeration value="green"/>
                        <enumeration value="white"/>
                        <enumeration value="blue"/>
                        <enumeration value="yellow"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="transparency">
                <complexType>
                    <attribute name="value" default="50">
                        <simpleType>
                            <restriction base="int">
                                <minInclusive value="0"/>
                                <maxInclusive value="100"/>
                            </restriction>
                        </simpleType>
                    </attribute>
                </complexType>
            </element>

            <element name="facets-number">
                <complexType>
                    <attribute name="value" use="required">
                        <simpleType>
                            <restriction base="int">
                                <minInclusive value="4"/>
                                <maxInclusive value="15"/>
                            </restriction>
                        </simpleType>
                    </attribute>
                </complexType>
            </element>
        </sequence>
    </complexType>

    <complexType name="SyntheticGem">
        <complexContent>
            <extension base="tns:Gem">
                <sequence>
                    <element name="laboratory" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== nikitun13/epam-training/task08-xml/src/test/resources/data/valid/10-gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://training.by/gems"
      xsi:schemaLocation="http://training.by/gems ../gems.xsd">
    <gem id="x1">
        <name>Diamond</name>
        <preciousness>precious</preciousness>
        <origin>Australia</origin>
        <visual-parameters>
            <color>white</color>
            <transparency value="40"/>
            <facets-number value="10"/>
        </visual-parameters>
        <value>5</value>
        <date>2021-10-08</date>
    </gem>

    <synthetic-gem id="x16">
        <name>Emerald</name>
        <preciousness>precious</preciousness>
        <origin>Switzerland</origin>
        <visual-parameters>
            <color>green</color>
            <transparency/>
            <facets-number value="6"/>
        </visual-parameters>
        <value>5</value>
        <date>2021-10-13</date>
        <laboratory>SSEF Lab</laboratory>
    </synthetic-gem>
</gems>

=== nikitun13/epam-training/task08-xml/src/test/resources/data/valid/07-gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://training.by/gems"
      xsi:schemaLocation="http://training.by/gems ../gems.xsd">
    <gem id="x1">
        <name>Diamond</name>
        <preciousness>precious</preciousness>
        <origin>Australia</origin>
        <visual-parameters>
            <color>white</color>
            <transparency value="40"/>
            <facets-number value="10"/>
        </visual-parameters>
        <value>5</value>
        <date>2021-10-08</date>
    </gem>
</gems>

=== nikitun13/epam-training/task08-xml/src/test/resources/data/valid/05-gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://training.by/gems"
      xsi:schemaLocation="http://training.by/gems ../gems.xsd">
    <gem id="x5">
        <name>Heliodor</name>
        <preciousness>semiprecious</preciousness>
        <origin>Russia</origin>
        <visual-parameters>
            <color>yellow</color>
            <transparency value="5"/>
            <facets-number value="8"/>
        </visual-parameters>
        <value>7</value>
        <date>2021-10-09</date>
    </gem>

    <gem id="x6">
        <name>Sapphire</name>
        <preciousness>precious</preciousness>
        <origin>USA</origin>
        <visual-parameters>
            <color>blue</color>
            <transparency value="30"/>
            <facets-number value="12"/>
        </visual-parameters>
        <value>11</value>
        <date>2021-10-09</date>
    </gem>

    <gem id="x7">
        <name>Alexandrite</name>
        <preciousness>precious</preciousness>
        <origin>South Africa</origin>
        <visual-parameters>
            <color>green</color>
            <transparency value="7"/>
            <facets-number value="15"/>
        </visual-parameters>
        <value>15</value>
        <date>2021-10-10</date>
    </gem>

    <synthetic-gem id="x8">
        <name>Diamond</name>
        <preciousness>precious</preciousness>
        <origin>Britain</origin>
        <visual-parameters>
            <color>white</color>
            <transparency/>
            <facets-number value="11"/>
        </visual-parameters>
        <value>13</value>
        <date>2021-10-04</date>
        <laboratory>De Beers</laboratory>
    </synthetic-gem>

    <synthetic-gem id="x9">
        <name>Emerald</name>
        <preciousness>precious</preciousness>
        <origin>Russia</origin>
        <visual-parameters>
            <color>green</color>
            <transparency/>
            <facets-number value="14"/>
        </visual-parameters>
        <value>16</value>
        <date>2021-10-06</date>
        <laboratory>Alrosa</laboratory>
    </synthetic-gem>

    <gem id="x10">
        <name>Garnet</name>
        <preciousness>semiprecious</preciousness>
        <origin>Russia</origin>
        <visual-parameters>
            <color>red</color>
            <transparency value="30"/>
            <facets-number value="4"/>
        </visual-parameters>
        <value>5</value>
        <date>2021-09-30</date>
    </gem>

    <gem id="x11">
        <name>Demantoid</name>
        <preciousness>semiprecious</preciousness>
        <origin>Italy</origin>
        <visual-parameters>
            <color>green</color>
            <transparency/>
            <facets-number value="15"/>
        </visual-parameters>
        <value>7</value>
        <date>2021-09-27</date>
    </gem>

    <gem id="x12">
        <name>Eremeevit</name>
        <preciousness>semiprecious</preciousness>
        <origin>France</origin>
        <visual-parameters>
            <color>blue</color>
            <transparency value="90"/>
            <facets-number value="5"/>
        </visual-parameters>
        <value>2</value>
        <date>2021-10-11</date>
    </gem>

    <synthetic-gem id="x13">
        <name>Cordierite</name>
        <preciousness>semiprecious</preciousness>
        <origin>USA</origin>
        <visual-parameters>
            <color>blue</color>
            <transparency/>
            <facets-number value="4"/>
        </visual-parameters>
        <value>7</value>
        <date>2021-10-11</date>
        <laboratory>GIA Gem Lab</laboratory>
    </synthetic-gem>

    <synthetic-gem id="x14">
        <name>Rhodochrosite</name>
        <preciousness>semiprecious</preciousness>
        <origin>Germany</origin>
        <visual-parameters>
            <color>red</color>
            <transparency value="30"/>
            <facets-number value="5"/>
        </visual-parameters>
        <value>1</value>
        <date>2021-10-07</date>
        <laboratory>Gubelin Gem Lab</laboratory>
    </synthetic-gem>

    <gem id="x15">
        <name>Diamond</name>
        <preciousness>precious</preciousness>
        <origin>Botswana</origin>
        <visual-parameters>
            <color>white</color>
            <transparency value="90"/>
            <facets-number value="8"/>
        </visual-parameters>
        <value>2</value>
        <date>2021-10-09</date>
    </gem>

    <synthetic-gem id="x16">
        <name>Emerald</name>
        <preciousness>precious</preciousness>
        <origin>Switzerland</origin>
        <visual-parameters>
            <color>green</color>
            <transparency/>
            <facets-number value="6"/>
        </visual-parameters>
        <value>5</value>
        <date>2021-10-13</date>
        <laboratory>SSEF Lab</laboratory>
    </synthetic-gem>
</gems>

=== nikitun13/epam-training/task08-xml/src/test/resources/data/valid/09-gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://training.by/gems"
      xsi:schemaLocation="http://training.by/gems ../gems.xsd">
    <synthetic-gem id="x16">
        <name>Emerald</name>
        <preciousness>precious</preciousness>
        <origin>Switzerland</origin>
        <visual-parameters>
            <color>green</color>
            <transparency/>
            <facets-number value="6"/>
        </visual-parameters>
        <value>5</value>
        <date>2021-10-13</date>
        <laboratory>SSEF Lab</laboratory>
    </synthetic-gem>
</gems>

=== nikitun13/epam-training/task08-xml/src/test/resources/data/valid/12-gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://training.by/gems"
      xsi:schemaLocation="http://training.by/gems ../gems.xsd">
    <gem id="x2">
        <name>Emerald</name>
        <preciousness>precious</preciousness>
        <origin>Brazil</origin>
        <visual-parameters>
            <color>green</color>
            <transparency value="10"/>
            <facets-number value="5"/>
        </visual-parameters>
        <value>3.5</value>
        <date>2021-10-05</date>
    </gem>
</gems>

=== nikitun13/epam-training/task08-xml/src/test/resources/data/valid/06-gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://training.by/gems"
      xsi:schemaLocation="http://training.by/gems ../gems.xsd">
    <gem id="x1">
        <name>Diamond</name>
        <preciousness>precious</preciousness>
        <origin>Australia</origin>
        <visual-parameters>
            <color>white</color>
            <transparency value="40"/>
            <facets-number value="10"/>
        </visual-parameters>
        <value>5</value>
        <date>2021-10-08</date>
    </gem>

    <gem id="x2">
        <name>Emerald</name>
        <preciousness>precious</preciousness>
        <origin>Brazil</origin>
        <visual-parameters>
            <color>green</color>
            <transparency value="10"/>
            <facets-number value="5"/>
        </visual-parameters>
        <value>3.5</value>
        <date>2021-10-05</date>
    </gem>

    <synthetic-gem id="x3">
        <name>Ruby</name>
        <preciousness>precious</preciousness>
        <origin>India</origin>
        <visual-parameters>
            <color>red</color>
            <transparency/>
            <facets-number value="15"/>
        </visual-parameters>
        <value>10</value>
        <date>2021-10-05</date>
        <laboratory>Gemstone Laboratory</laboratory>
    </synthetic-gem>

    <synthetic-gem id="x4">
        <name>Aquamarine</name>
        <preciousness>semiprecious</preciousness>
        <origin>India</origin>
        <visual-parameters>
            <color>blue</color>
            <transparency value="60"/>
            <facets-number value="7"/>
        </visual-parameters>
        <value>5</value>
        <date>2021-10-03</date>
        <laboratory>Gemstone Laboratory</laboratory>
    </synthetic-gem>
</gems>

=== nikitun13/epam-training/task08-xml/src/test/resources/data/valid/08-gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://training.by/gems"
      xsi:schemaLocation="http://training.by/gems ../gems.xsd">
    <gem id="x5">
        <name>Heliodor</name>
        <preciousness>semiprecious</preciousness>
        <origin>Russia</origin>
        <visual-parameters>
            <color>yellow</color>
            <transparency value="5"/>
            <facets-number value="8"/>
        </visual-parameters>
        <value>7</value>
        <date>2021-10-09</date>
    </gem>
</gems>

=== nikitun13/epam-training/task08-xml/src/test/resources/data/valid/01-gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://training.by/gems"
      xsi:schemaLocation="http://training.by/gems ../gems.xsd">
    <synthetic-gem id="x3">
        <name>Ruby</name>
        <preciousness>precious</preciousness>
        <origin>India</origin>
        <visual-parameters>
            <color>red</color>
            <transparency/>
            <facets-number value="15"/>
        </visual-parameters>
        <value>10</value>
        <date>2021-10-05</date>
        <laboratory>Gemstone Laboratory</laboratory>
    </synthetic-gem>

    <synthetic-gem id="x4">
        <name>Aquamarine</name>
        <preciousness>semiprecious</preciousness>
        <origin>India</origin>
        <visual-parameters>
            <color>blue</color>
            <transparency value="60"/>
            <facets-number value="7"/>
        </visual-parameters>
        <value>5</value>
        <date>2021-10-03</date>
        <laboratory>Gemstone Laboratory</laboratory>
    </synthetic-gem>

    <synthetic-gem id="x8">
        <name>Diamond</name>
        <preciousness>precious</preciousness>
        <origin>Britain</origin>
        <visual-parameters>
            <color>white</color>
            <transparency/>
            <facets-number value="11"/>
        </visual-parameters>
        <value>13</value>
        <date>2021-10-04</date>
        <laboratory>De Beers</laboratory>
    </synthetic-gem>

    <synthetic-gem id="x9">
        <name>Emerald</name>
        <preciousness>precious</preciousness>
        <origin>Russia</origin>
        <visual-parameters>
            <color>green</color>
            <transparency/>
            <facets-number value="14"/>
        </visual-parameters>
        <value>16</value>
        <date>2021-10-06</date>
        <laboratory>Alrosa</laboratory>
    </synthetic-gem>

    <synthetic-gem id="x13">
        <name>Cordierite</name>
        <preciousness>semiprecious</preciousness>
        <origin>USA</origin>
        <visual-parameters>
            <color>blue</color>
            <transparency/>
            <facets-number value="4"/>
        </visual-parameters>
        <value>7</value>
        <date>2021-10-11</date>
        <laboratory>GIA Gem Lab</laboratory>
    </synthetic-gem>

    <synthetic-gem id="x14">
        <name>Rhodochrosite</name>
        <preciousness>semiprecious</preciousness>
        <origin>Germany</origin>
        <visual-parameters>
            <color>red</color>
            <transparency value="30"/>
            <facets-number value="5"/>
        </visual-parameters>
        <value>1</value>
        <date>2021-10-07</date>
        <laboratory>Gubelin Gem Lab</laboratory>
    </synthetic-gem>

    <synthetic-gem id="x16">
        <name>Emerald</name>
        <preciousness>precious</preciousness>
        <origin>Switzerland</origin>
        <visual-parameters>
            <color>green</color>
            <transparency/>
            <facets-number value="6"/>
        </visual-parameters>
        <value>5</value>
        <date>2021-10-13</date>
        <laboratory>SSEF Lab</laboratory>
    </synthetic-gem>
</gems>
